### ISSUE TITLE
Xamarin Studio Use

### ISSUE THREAD

**Issue by kswain1** [r1pper/GoPro.Hero#12]
Has anyone tried to use this library with Xamarin Studio, if so did you get a Unsupported PCL profile .Net Profile error?

**Comment by r1pper** [comment]
Hello @kswain1 
I'm glad that you found the library useful

I developed the library with Visual Studio 2012 and never tested it with Xamarin Studio before, however I was able to make it work in **Xamarin Studio 5.5.3- Build 6**  on Windows (latest version at the moment), Here are the Steps I took:

**1- Unload/Remove Unsupported Projects:** Because I used MsTest for unit tests, GoPro.Hero.Tests is not supported by Xamarin Studio, so in this case we can either unload or remove it.
GoPro.Hero.WinForms sample is obsolete and does not exist anymore, so we can safely remove it too.

**2-Updating Relevant Packages:** to make it work, we should update `Microsoft.Bcl`, `Microsoft.Bcl.Async` and `Microsoft.Bcl.Build` Nuget packages (in Xamarin Studio we should right-click on the package and select update). We should do the same thing for **GoPro.Hero.Extensions** project too. _(Do not Update Json.Net to 6.0.6, it's not compatible with profile 96)_.

that's it, I hope you find it helpful.

**Comment by kswain1** [comment]
Well I did that, but when I tried to update the Microsoft.Bcl.Build it deleted the files and fail to complete the update because it was compatible with JSON.Net http://json.net/ profile 96.

**Comment by r1pper** [comment]
Are you sure you have PCL installed on your machine?
this post may help [PCl Tips and Tricks](http://xamarinandroid.blogspot.nl/2014/06/portable-class-librarypcl-setup-for.html)

I posted more detailed answer to your question on [Stack overflow](http://stackoverflow.com/questions/26812605/unsupported-pcl-profile-xamarin) based on the mentioned Post.

by the way you can compile it with Visual studio (or I can give you compiled assemblies) and use it in your xamarin projects.

**Comment by kswain1** [comment]
Yes, may you give me the compiled assemblies for Tamarin. Take Care,
Kehlin Swain 

```
  From: r1pper <notifications@github.com>
```

 To: r1pper/GoPro.Hero GoPro.Hero@noreply.github.com 
Cc: Kehlin Swain kehlinswain@yahoo.com 
 Sent: Monday, November 24, 2014 2:13 PM
 Subject: Re: [GoPro.Hero] Xamarin Studio Use (#12)

Are you sure you have PCL installed on your machine?
this post may help PCl Tips and TricksI posted more detailed answer to your question on Stack overflow based on the mentioned Post.by the way you can compile it with Visual studio (or I can give you compiled assemblies) and use it in your xamarin projects.—

**Comment by kswain1** [comment]
Also, Thank you for going out of your to help me out. Take Care,
Kehlin Swain 

```
  From: r1pper <notifications@github.com>
```

 To: r1pper/GoPro.Hero GoPro.Hero@noreply.github.com 
Cc: Kehlin Swain kehlinswain@yahoo.com 
 Sent: Monday, November 24, 2014 2:13 PM
 Subject: Re: [GoPro.Hero] Xamarin Studio Use (#12)

Are you sure you have PCL installed on your machine?
this post may help PCl Tips and TricksI posted more detailed answer to your question on Stack overflow based on the mentioned Post.by the way you can compile it with Visual studio (or I can give you compiled assemblies) and use it in your xamarin projects.—

**Comment by r1pper** [comment]
Here is the link to Xamarin Project and Compiled assemblies

https://drive.google.com/file/d/0BwXXVib73b6DYmRoZm8wUzlVQkE/view?usp=sharing

best regards
